DROP INDEX country_region;
DROP INDEX jobs_author;
DROP INDEX jobs_dates;
DROP INDEX jobs_foreign;
DROP INDEX jobs_manager;
DROP INDEX location_country;
DROP TABLE applications;
DROP TABLE jobs;
DROP TABLE function;
DROP TABLE grade;
DROP TABLE relocation;
DROP TABLE location;
DROP TABLE country;
DROP TABLE region;
DROP TABLE interview_status;
DROP TABLE manager_review;
DROP TABLE offer_status;
EXIT;
