CREATE INDEX TRANSACTIONS_NUK01
ON TRANSACTIONS_TB
(
  HR_ADMIN
)
  STORAGE(initial 10M next 1M pctincrease 0)
  TABLESPACE WWW_GENERAL_IND02
;

CREATE INDEX TRANSACTIONS_NUK02
ON TRANSACTIONS_TB
(
  TRANS_TYPE
)
  STORAGE(initial 10M next 1M pctincrease 0)
  TABLESPACE WWW_GENERAL_IND02
;

CREATE INDEX TRANSACTIONS_NUK03
ON TRANSACTIONS_TB
(
  REJECT_REASON
)
  STORAGE(initial 10M next 1M pctincrease 0)
  TABLESPACE WWW_GENERAL_IND02
;

CREATE INDEX TRANSACTIONS_NUK04
ON TRANSACTIONS_TB
(
  TRANS_CENTER
)
  STORAGE(initial 10M next 1M pctincrease 0)
  TABLESPACE WWW_GENERAL_IND02
;

CREATE INDEX TRANSACTIONS_NUK_05
ON TRANSACTIONS_TB
(
  EMP_CID
)
  STORAGE (initial 10M next 1K pctincrease 0)
  TABLESPACE WWW_GENERAL_IND02
; 
CREATE BITMAP INDEX TRANSACTIONS_NUK_06
ON TRANSACTIONS_TB
(
  STATUS
)
  STORAGE (initial 10M next 1M pctincrease 0)
  TABLESPACE WWW_GENERAL_IND02
;
