DECLARE FUNCTION GETKEY$ ()
TYPE MARKTYPE
 K AS INTEGER
END TYPE
DIM JUNIOR(6, 11) AS INTEGER, MAR AS MARKTYPE

SCREEN 0: CLS
OPEN "GRADES.FIL" FOR RANDOM AS #1 LEN = 2
GOSUB SHOWDATA
 DO
 LOOP WHILE INKEY$ = ""
GOSUB SHOWGRAPH
 END
GOSUB EDITDATA




EDITDATA:
 LET YEAR = 1: SUBJECT = 1
 DO
  M% = 0
   DO
    LOCATE 6 + SUBJECT, 15 + YEAR * 8 + M% MOD 2, 1
    A$ = GETKEY$

    IF ASC(A$) > 47 AND ASC(A$) < 58 THEN
      IF M% MOD 2 = 0 THEN MAR.K = VAL(A$) * 10
      IF M% MOD 2 = 1 THEN MAR.K = MAR.K + VAL(A$)
      LOCATE 6 + SUBJECT, 15 + YEAR * 8: PRINT USING "##"; MAR.K
      M% = M% + 1
    END IF
   LOOP UNTIL LEN(A$) > 2
  IF M% <> 0 THEN PUT #1, (YEAR - 1) * 11 + SUBJECT, MAR.K
  IF A$ = "UPP" THEN SUBJECT = SUBJECT - 1: IF SUBJECT < 1 THEN SUBJECT = 1
  IF A$ = "DOWN" THEN SUBJECT = SUBJECT + 1: IF SUBJECT > 11 THEN SUBJECT = 11
  IF A$ = "LEFT" THEN YEAR = YEAR - 1: IF YEAR < 1 THEN YEAR = 1
  IF A$ = "RIGHT" THEN YEAR = YEAR + 1: IF YEAR > 6 THEN YEAR = 6
 LOOP
RETURN

SHOWDATA:

LOCATE 5, 5
PRINT "             1988            1989            1990            1991"
LOCATE 6, 5
PRINT "                X.MAS   SUMMER  X.MAS   SUMMER  X.MAS   SUMMER"
LOCATE 18, 5
PRINT "                   1st YEAR        2nd YEAR        3rd YEAR"
RESTORE NAMES
FOR X = 1 TO 11
 READ NAME$: LOCATE 6 + X, 3: PRINT NAME$
NEXT X

FOR YEAR = 1 TO 6
 FOR SUBJECT = 1 TO 11
  GET #1, (YEAR - 1) * 11 + SUBJECT, MAR.K
  JUNIOR(YEAR, SUBJECT) = MAR.K
  LOCATE 6 + SUBJECT, 15 + YEAR * 8: PRINT USING "##"; MAR.K
 NEXT SUBJECT
NEXT YEAR

RETURN

NAMES:
 DATA "ENGLISH  ","IRISH    ","LATIN    ","FRENCH   ","GERMAN   ","MATHS    "
 DATA "HISTORY  ","GEOGRAPHY","MUSIC    ","COMMERCE ","SCIENCE  "    
 

TYPE YEARTYPE
 ENG AS INTEGER
 IRI AS INTEGER
 LAT AS INTEGER
 FRN AS INTEGER
 GER AS INTEGER
 MAT AS INTEGER
 HIS AS INTEGER
 GEO AS INTEGER
 MUS AS INTEGER
 CMC AS INTEGER
 SCI AS INTEGER
END TYPE


FOR YEAR = 1 TO 6
  LOCATE 1, 70: PRINT 1988 + YEAR \ 2;
  IF YEAR MOD 2 = 1 THEN PRINT "[C]";  ELSE PRINT "[S]";
 RESTORE NAMES
 FOR SUBJECT = 1 TO 11
  READ NAME$
   LOCATE SUBJECT * 2, 5: PRINT NAME$; " MARK:     "
   DO
    LOCATE SUBJECT * 2, 21 + M% MOD 2, 1
    'NUM = GETKEY - 48

    IF NUM > -1 AND NUM < 10 THEN
      IF M% MOD 2 = 0 THEN MAR.K = NUM * 10
      IF M% MOD 2 = 1 THEN MAR.K = MAR.K + NUM
      LOCATE SUBJECT * 2, 21: PRINT USING "##"; MAR.K
      M% = M% + 1
    END IF
   LOOP UNTIL NUM = -35
   PUT #1, (YEAR - 1) * 11 + SUBJECT, MAR.K
 NEXT SUBJECT
NEXT YEAR

FUNCTION GETKEY$

DO
 A$ = INKEY$
LOOP WHILE A$ = ""

IF ASC(A$) = 27 THEN END
IF A$ = CHR$(0) + CHR$(72) THEN A$ = "UPP"
IF A$ = CHR$(0) + CHR$(80) THEN A$ = "DOWN"
IF A$ = CHR$(0) + CHR$(75) THEN A$ = "LEFT"
IF A$ = CHR$(0) + CHR$(77) THEN A$ = "RIGHT"

GETKEY$ = A$

END FUNCTION

SUB SHOWGRAPH (SUBJECT1%, SUBJECT2%)

 SCREEN 1: CLS
 LINE (250, 150)-(45, 150), 3
 LINE (45, 150)-(45, 50), 3
 LINE (43, 50)-(47, 50), 3: LOCATE 7, 2: PRINT "100%"
 LINE (43, 110)-(47, 110), 3: LOCATE 14, 3: PRINT "40%"
 LINE (50, 148)-(50, 152), 3: LOCATE 20, 7: PRINT "C"
 LINE (100, 148)-(100, 152), 3: LOCATE 20, 13: PRINT "S"
 LINE (150, 148)-(150, 152), 3: LOCATE 20, 19: PRINT "C"
 LINE (200, 148)-(200, 152), 3: LOCATE 20, 26: PRINT "S"
 LINE (250, 148)-(250, 152), 3: LOCATE 20, 32: PRINT "C"
 RESTORE NAMES
 LINE (60, 12)-(75, 12), 1: READ NAME$: LOCATE 2, 11: PRINT NAME$
 LINE (170, 12)-(185, 12), 2: READ NAME$: LOCATE 2, 25: PRINT NAME$

 PSET (50, 150 - JUNIOR(1, SUBJECT1%))
 FOR YEAR = 2 TO 5
  LINE STEP(0, 0)-(YEAR * 50, 150 - JUNIOR(YEAR, SUBJECT1%)), 1
 NEXT YEAR
 PSET (50, 150 - JUNIOR(1, SUBJECT2%))
 FOR YEAR = 2 TO 5
  LINE STEP(0, 0)-(YEAR * 50, 150 - JUNIOR(YEAR, SUBJECT2%)), 2
 NEXT YEAR

END SUB

