REM README
REM NOTES ON "LIST"
REM PAUL EGAN (22/10/1992)
ON KEY(10) GOSUB PES: KEY(10) ON
CLS
SCREEN 0
COLOR 2
PRINT , "       ษอออออออออออออออออออออออออออป"
PRINT , "       บ A COUPLE OF NOTES ON LIST บ"
PRINT , "       ศอออออออออออออออออออออออออออผ"
COLOR 3
PRINT ""
PRINT "         THE EXE FILES ON THE DISK, ALTHOUGH SEPERATE, ARE ACTUALLY"
PRINT "           ALL THE SAME PROGRAM LINKED TOGETHER WITH THE `CHAIN' COMMAND"
PRINT "         TO START SIMPLY TYPE `AUTO' "
PRINT "         THE BATCH FILE `AUTO' OPENS `INTRO' WHICH IN TURN GOES TO  "
PRINT "           EITHER `PASSBALL' OR `LIST'.  ESCAPING FROM `LIST' BRINGS "
PRINT "           YOU TO `PASS'.  `TENNIS' AND `BALL' ARE JUST GAMES."
PRINT "         `LIST' IS THE MAIN PROGRAM WHICH ALLOWS SELECT AND LOAD THE "
PRINT "           GAMES/APPLICATIONS OF YOUR CHOICE.  OBVIOUSLY IT WILL ONLY"
PRINT "           WORK ON MY COMPUTER AS IT IS SET FOR CERTAIN DIRECTORIES AND"
PRINT "           PROGRAMS."
PRINT "         `INTRO' WILL PERHAPS BE THE MOST INTERESTING TO YOU BECAUSE IT"
PRINT "           INVOLVES THE PASSWORD.  YOU CANNOT ESCAPE OUT OF THIS PROGRAM"
PRINT "           AND THE `PASSBALL' PART (WHICH I ONLY PUT IN FOR FUN), WHEN YOU"
PRINT "           GET THE INCORRECT PASSWORD,  CAN EASILY BE EXCHANGED FOR A "
PRINT "           TOTAL SHUTDOWN."
PRINT "         `PASS' IS BASICALLY THE SAME AS `INTRO' BUT IT DOESN'T HAVE THE "
PRINT "           OPENING SCREEN AND THE PASSWORD IS LONGER."
PRINT "         DISK 2 CONTAINS THE ORIGINAL BASIC FILES FOR WHICH YOU WILL NEED"
PRINT "           QUICK BASIC TO SEE."
LOCATE 2, 55: COLOR 20: PRINT "F10 TO EXIT"
EVER:
 GOTO EVER
PES:
COLOR 5
LOCATE 10, 22: PRINT "ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ"
LOCATE 11, 22: PRINT "ณ                            ณ"
LOCATE 12, 22: PRINT "ณ  P.S.  THE PASSWORD FOR    ณ"
LOCATE 13, 22: PRINT "ณ  `INTRO' IS OPEN AND FOR   ณ"
LOCATE 14, 22: PRINT "ณ  `PASS' IT'S PLEASE.       ณ"
LOCATE 15, 22: PRINT "ณ  ALTHOUGH YOU MIGHT WANT   ณ"
LOCATE 16, 22: PRINT "ณ  TO FAIL IN `INTRO' TO     ณ"
LOCATE 17, 22: PRINT "ณ  HAVE A LOOK AT `PASSBALL' ณ"
LOCATE 18, 22: PRINT "ณ                            ณ"
LOCATE 19, 22: PRINT "ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู"
FOR PAUSE = 1 TO 2500: NEXT PAUSE
CLS
END

