REM AUTO
ON KEY(10) GOSUB PEXIT: KEY(10) ON
ON KEY(11) GOSUB UPUP: KEY(11) ON
ON KEY(12) GOSUB LEFTLEFT: KEY(12) ON
ON KEY(13) GOSUB RIGHTRIGHT: KEY(13) ON
ON KEY(14) GOSUB DOWNDOWN: KEY(14) ON
ON KEY(2) GOSUB OTHER: KEY(2) ON
ON KEY(1) GOSUB PHELP: KEY(1) ON
ON KEY(9) GOSUB VEND: KEY(9) ON
KEY 15, CHR$(&H0) + CHR$(&HF)
ON KEY(6) GOSUB PTAB: KEY(6) ON
ON ERROR GOTO PERR
WIDTH 40
SCREEN 0
START:
COLOR 7, 0
CLS
LOCATE 1, 1
COLOR 1, 1
PRINT "                                       "
COLOR 12, 1
PRINT "       G A M E S   L I S T I N G       "
PRINT "      อออออออออออออออออออออออออออ      "
COLOR 1, 1
PRINT "                                       "
COLOR 4, 1
LOCATE 22, 1, 0
PRINT " USE CURSOR KEYS AND RETURN TO SELECT  "
COLOR 11, 1
PRINT "   F10 ๐ EXIT TO DOS      F1 ๐ HELP    "
LOCATE 7, 1: COLOR 2, 0
PRINT "  SIMCITY           CALIFORNIA GAMES"
PRINT : PRINT "  F19 STEALTH       PRINCE OF PERSIA"
PRINT : PRINT "                    WORLD TOUR GOLF "
LOCATE 11, 1: COLOR 8, 0: PRINT "  LEMMINGS"
COLOR 8, 0
PRINT : PRINT "                    FLIGHT SIMULATOR"
LOCATE 13, 1: COLOR 2, 0: PRINT "  GRAND PRIX"
COLOR 3, 0: LOCATE 16, 15
PRINT "TOOLS ..."
COLOR 3, 0
LOCATE 18, 12
PRINT "OTHER GAMES ..."
IF T = 2 GOTO OGAMES
IF T = 3 GOTO HELP
IF T = 4 GOTO TOOL
LHS:
SIDE = 1
COLOR 2, 7
LOCATE 7, 3
PRINT "SIMCITY"
P = 1
GOTO RET
REM UPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUPUP
UPUP:
 KEY(11) ON
 IF P = 1 GOTO UP1
 IF P = 2 GOTO UP2
 IF P = 3 GOTO UP3
 IF P = 4 GOTO UP4
 IF P = 5 GOTO UP5
 IF P = 6 GOTO UP6
 IF P = 7 GOTO UP7
 IF P = 8 GOTO UP8
 IF P = 9 GOTO UP9
 IF P = 0 GOTO UP0
GOTO RET
REM LEFTLEFTLEFTLEFTLEFTLEFTLEFTLEFTLEFTLEFTLEFTLEFT
LEFTLEFT:
 KEY(12) ON
 IF P = 1 GOTO LEFT1
 IF P = 2 GOTO LEFT2
 IF P = 3 GOTO LEFT3
 IF P = 4 GOTO LEFT4
 IF P = 5 GOTO LEFT5
 IF P = 6 GOTO LEFT6
 IF P = 7 GOTO LEFT7
 IF P = 8 GOTO LEFT8
 IF P = 9 GOTO LEFT9
 IF P = 0 GOTO LEFT0
GOTO RET
REM RIGHTRIGHTRIGHTRIGHTRIGHTRIGHTRIGHTRIGHTRIGHT
RIGHTRIGHT:
 KEY(13) ON
 IF P = 1 GOTO LEFT1
 IF P = 2 GOTO LEFT2
 IF P = 3 GOTO LEFT3
 IF P = 4 GOTO LEFT4
 IF P = 5 GOTO LEFT5
 IF P = 6 GOTO LEFT6
 IF P = 7 GOTO LEFT7
 IF P = 8 GOTO LEFT8
 IF P = 9 GOTO LEFT9
 IF P = 0 GOTO LEFT0
GOTO RET
REM DOWNDOWNDOWNDOWNDOWNDOWNDOWNDOWNDOWNDOWNDOWNDOWN
DOWNDOWN:
 KEY(14) ON
 IF P = 1 GOTO DOWN1
 IF P = 2 GOTO DOWN2
 IF P = 3 GOTO DOWN3
 IF P = 4 GOTO DOWN4
 IF P = 5 GOTO DOWN5
 IF P = 6 GOTO DOWN6
 IF P = 7 GOTO DOWN7
 IF P = 8 GOTO DOWN8
 IF P = 9 GOTO DOWN9
 IF P = 0 GOTO DOWN0
GOTO RET
RET:         
DO
 A$ = INKEY$
LOOP UNTIL A$ = ""
RLOOP:
 X$ = INKEY$
 IF X$ <> "" THEN GOTO ROUT
GOTO RLOOP
ROUT:
 IF X$ = "Q" THEN GOTO UPUP
 IF X$ = "A" THEN GOTO DOWNDOWN
 IF X$ = "O" THEN GOTO LEFTLEFT
 IF X$ = "P" THEN GOTO RIGHTRIGHT
 IF X$ = CHR$(13) THEN GOTO RENAME
GOTO RET
RENAME:
 IF P = 1 THEN PRINT "1"
 IF P = 2 THEN PRINT "2"
 IF P = 3 THEN PRINT "3"
 IF P = 4 THEN PRINT "4"
 IF P = 5 THEN PRINT "5"
 IF P = 6 THEN PRINT "6"
 IF P = 7 THEN PRINT "7"
 IF P = 8 THEN GOTO GSORRY
 IF P = 9 THEN GOTO PTOOL
 IF P = 0 THEN GOTO OTHER
END
PEXIT:
 NAME "X" AS "E"
 CHAIN "PASS"
END
OTHER:
 WIDTH 80
 T = 2
 IF PTIME = 21 GOTO GAMRET
 GOTO START
END
REM CHANGECHANGECHANGECHANGECHANGECHANGECHANGECHANGE
REM CHANGECHANGECHANGECHANGECHANGECHANGECHANGECHANGE
SIMA:
 LOCATE 7, 3: COLOR 2, 0: PRINT "SIMCITY": RETURN
SIMB:
 LOCATE 7, 3: COLOR 2, 7: PRINT "SIMCITY": RETURN
CALA:
 LOCATE 7, 21: COLOR 2, 0: PRINT "CALIFORNIA GAMES": RETURN
CALB:
 LOCATE 7, 21: COLOR 2, 7: PRINT "CALIFORNIA GAMES": RETURN
F19A:
 LOCATE 9, 3: COLOR 2, 0: PRINT "F19 STEALTH": RETURN
F19B:
 LOCATE 9, 3: COLOR 2, 7: PRINT "F19 STEALTH": RETURN
POPA:
 LOCATE 9, 21: COLOR 2, 0: PRINT "PRINCE OF PERSIA": RETURN
POPB:
 LOCATE 9, 21: COLOR 2, 7: PRINT "PRINCE OF PERSIA": RETURN
LEMA:
 LOCATE 11, 3: COLOR 8, 0: PRINT "LEMMINGS": RETURN
LEMB:
 LOCATE 11, 3: COLOR 8, 7: PRINT "LEMMINGS": RETURN
WTGA:
 LOCATE 11, 21: COLOR 2, 0: PRINT "WORLD TOUR GOLF": RETURN
WTGB:
 LOCATE 11, 21: COLOR 2, 7: PRINT "WORLD TOUR GOLF": RETURN
GRPA:
 LOCATE 13, 3: COLOR 2, 0: PRINT "GRAND PRIX": RETURN
GRPB:
 LOCATE 13, 3: COLOR 2, 7: PRINT "GRAND PRIX": RETURN
FLSA:
 LOCATE 13, 21: COLOR 8, 0: PRINT "FLIGHT SIMULATOR": RETURN
FLSB:
 LOCATE 13, 21: COLOR 8, 7: PRINT "FLIGHT SIMULATOR": RETURN
TOLA:
 LOCATE 16, 15: COLOR 3, 0: PRINT "TOOLS ...": RETURN
TOLB:
 LOCATE 16, 15: COLOR 3, 7: PRINT "TOOLS ...": RETURN
GAMA:
 LOCATE 18, 12: COLOR 3, 0: PRINT "OTHER GAMES ...": RETURN
GAMB:
 LOCATE 18, 12: COLOR 3, 7: PRINT "OTHER GAMES ...": RETURN
REM MOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVE
REM MOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVEMOVE
UP1:
 GOSUB SIMA: GOSUB GAMB: P = 0: GOTO RET
UP2:
 GOSUB CALA: GOSUB GAMB: P = 0: GOTO RET
UP3:
 GOSUB F19A: GOSUB SIMB: P = 1: GOTO RET
UP4:
 GOSUB POPA: GOSUB CALB: P = 2: GOTO RET
UP5:
 GOSUB LEMA: GOSUB F19B: P = 3: GOTO RET
UP6:
 GOSUB WTGA: GOSUB POPB: P = 4: GOTO RET
UP7:
 GOSUB GRPA: GOSUB LEMB: P = 5: GOTO RET
UP8:
 GOSUB FLSA: GOSUB WTGB: P = 6: GOTO RET
UP9:
 GOSUB TOLA: GOSUB FLSB: P = 8: GOTO RET
UP0:
 GOSUB GAMA: GOSUB TOLB: P = 9: GOTO RET
LEFT1:
 GOSUB SIMA: GOSUB CALB: P = 2: GOTO RET
LEFT2:
 GOSUB CALA: GOSUB SIMB: P = 1: GOTO RET
LEFT3:
 GOSUB F19A: GOSUB POPB: P = 4: GOTO RET
LEFT4:
 GOSUB POPA: GOSUB F19B: P = 3: GOTO RET
LEFT5:
 GOSUB LEMA: GOSUB WTGB: P = 6: GOTO RET
LEFT6:
 GOSUB WTGA: GOSUB LEMB: P = 5: GOTO RET
LEFT7:
 GOSUB GRPA: GOSUB FLSB: P = 8: GOTO RET
LEFT8:
 GOSUB FLSA: GOSUB GRPB: P = 7: GOTO RET
LEFT9:
 BEEP: RETURN
LEFT0:
 BEEP: RETURN
DOWN1:
 GOSUB SIMA: GOSUB F19B: P = 3: GOTO RET
DOWN2:
 GOSUB CALA: GOSUB POPB: P = 4: GOTO RET
DOWN3:
 GOSUB F19A: GOSUB LEMB: P = 5: GOTO RET
DOWN4:
 GOSUB POPA: GOSUB WTGB: P = 6: GOTO RET
DOWN5:
 GOSUB LEMA: GOSUB GRPB: P = 7: GOTO RET
DOWN6:
 GOSUB WTGA: GOSUB FLSB: P = 8: GOTO RET
DOWN7:
 GOSUB GRPA: GOSUB TOLB: P = 9: GOTO RET
DOWN8:
 GOSUB FLSA: GOSUB TOLB: P = 9: GOTO RET
DOWN9:
 GOSUB TOLA: GOSUB GAMB: P = 0: GOTO RET
DOWN0:
 GOSUB GAMA: GOSUB SIMB: P = 1: GOTO RET
REM SORRYSORRYSORRYSORRYSORRYSORRYSORRYSORRYSORRYSORRY
REM SORRYSORRYSORRYSORRYSORRYSORRYSORRYSORRYSORRYSORRY
GSORRY:
COLOR 7, 0
LOCATE 10, 7: PRINT "ษออออออออออออออออออออออออป"
LOCATE 11, 7: PRINT "บ  SORRY NOT AVAILABLE   บ"
LOCATE 12, 7: PRINT "ศออออออออออออออออออออออออผ"
FOR PAUSE = 1 TO 500: NEXT PAUSE
LOCATE 10, 1: COLOR 2, 0
PRINT "                                    "
PRINT "                    WORLD TOUR GOLF "
PRINT "                                    "
X = 0: IF P = 5 THEN LET X = 7
LOCATE 11, 3: COLOR 8, X: PRINT "LEMMINGS"
IF SIDE = 3 GOTO GLOOP
GOTO RET
REM OTHERGAMESOTHERGAMESOTHERGAMESOTHERGAMESOTHERGAMES"
REM OTHERGAMESOTHERGAMESOTHERGAMESOTHERGAMESOTHERGAMES
OGAMES:
 COLOR 7, 0
 FOR R = 1 TO 23
 LOCATE R, 40
 PRINT CHR$(186)
 NEXT R
GAMBAK:
LOCATE 2, 1: COLOR 6, 1
PRINT "       G A M E S   L I S T I N G       "
PRINT "      อออออออออออออออออออออออออออ      "
LOCATE 1, 41: COLOR 1, 1
PRINT "                                       "
COLOR 12, 1: LOCATE 2, 41
PRINT "         O T H E R   G A M E S         "
LOCATE 3, 41
PRINT "        อออออออออออออออออออออออ        "
COLOR 1, 1: LOCATE 4, 41
PRINT "                                       "
IF PTIME = 21 GOTO GBRET
COLOR 4, 1: LOCATE 22, 1, 0
PRINT "                         PRESS THE LETTER OF YOUR CHOICE                        "
COLOR 11, 1: LOCATE 23, 1
PRINT "                        `X' SWITCHES TO THE GAMES LISTING                       "
LOCATE 7, 41: COLOR 2, 0
PRINT " (A)  ASTEROID      (B)  A-MAZE"
LOCATE 9, 41
PRINT " (C)  BRICKS        (D)  CENTIPEDE"
LOCATE 11, 41
PRINT " (E)  DIGGER        (F)  PACMAN"
LOCATE 13, 41
PRINT " (G)  PANGO         (H)  PARATROOPER"
LOCATE 15, 41
PRINT " (I)  SCRABBLE      (J)  SPACE INVADERS"
LOCATE 17, 41
PRINT " (K)  SOPWITH       (L)  BASIC GAMES"
LOCATE 18, 12: COLOR 3, 7
PRINT "OTHER GAMES ..."
GAMRET:
IF PTIME = 21 GOTO GAMBAK
GBRET:
SIDE = 2
DO
 O$ = INKEY$
 PRINT O$
LOOP UNTIL O$ = ""
FLOOP:
 A$ = INKEY$
 IF A$ <> "" THEN GOTO POUT
GOTO FLOOP
POUT:
IF A$ = "X" OR A$ = "x" GOTO PTAB
IF A$ = "A" OR A$ = "a" GOTO B1
IF A$ = "B" OR A$ = "b" GOTO B2
IF A$ = "C" OR A$ = "c" GOTO B3
IF A$ = "D" OR A$ = "d" GOTO B4
IF A$ = "E" OR A$ = "e" GOTO B5
IF A$ = "F" OR A$ = "f" GOTO B6
IF A$ = "G" OR A$ = "g" GOTO B7
IF A$ = "H" OR A$ = "h" GOTO B8
IF A$ = "I" OR A$ = "i" GOTO B9
IF A$ = "J" OR A$ = "j" GOTO B10
IF A$ = "K" OR A$ = "k" GOTO B11
IF A$ = "L" OR A$ = "l" GOTO B12
GOTO POUT
B1:
NAME "X" AS "B1": END
B2:
NAME "X" AS "B2": END
B3:
NAME "X" AS "B3": END
B4:
NAME "X" AS "B4": END
B5:
NAME "X" AS "B5": END
B6:
NAME "X" AS "B6": END
B7:
NAME "X" AS "B7": END
B8:
NAME "X" AS "B8": END
B9:
NAME "X" AS "B9": END
B10:
NAME "X" AS "B10": END
B11:
NAME "X" AS "B11": END
B12:
NAME "X" AS "B12": END
PTAB:
KEY(6) ON
IF SIDE = 2 GOTO POTH
IF SIDE = 3 GOTO PTOL
END
POTH:
COLOR 7, 0
FOR k = 19 TO 21
  LOCATE k, 41: PRINT "                                      "
NEXT k
COLOR 6, 1: LOCATE 2, 41
PRINT "         O T H E R   G A M E S         "
LOCATE 3, 41
PRINT "        อออออออออออออออออออออออ        "
LOCATE 2, 1: COLOR 12, 1
PRINT "       G A M E S   L I S T I N G       "
PRINT "      อออออออออออออออออออออออออออ      "
GOSUB GAMA
PTIME = 21
GOTO LHS
END
REM HELPHELPHELPHELPHELPHELPHELPHELPHELPHELPHELPHELP
REM HELPHELPHELPHELPHELPHELPHELPHELPHELPHELPHELPHELP
HELP:
 KEY(1) ON
 COLOR 7, 0
 FOR R = 1 TO 23
 LOCATE R, 40
 PRINT CHR$(186)
 NEXT R
LOCATE 2, 1: COLOR 12, 1
PRINT "       G A M E S   L I S T I N G       "
PRINT "      อออออออออออออออออออออออออออ      "
LOCATE 1, 41: COLOR 1, 1
PRINT "                                       "
COLOR 12, 1: LOCATE 2, 41
PRINT "              H  E  L  P               "
LOCATE 3, 41
PRINT "             ออออออออออออ              "
COLOR 1, 1: LOCATE 4, 41
PRINT "                                       "
COLOR 4, 1: LOCATE 22, 1, 0
PRINT "             COPYRIGHT EGAN SOFTWARE INC. 1992       VERSION  3.0              "
COLOR 11, 1: LOCATE 23, 1
PRINT "        PROGRAMMER: PAUL EGAN   GRAPHICS: PAUL EGAN   SOUND: PAUL EGAN         "
COLOR 14, 0: LOCATE 6, 41: PRINT "  GAMES LISTING:    "
COLOR 3, 0: LOCATE 7, 41: PRINT "    Use the "
COLOR 5, 0: LOCATE 7, 53: PRINT "arrow keys on the keypad"
COLOR 3, 0: LOCATE 8, 41: PRINT "    not the seperate ones and when your"
LOCATE 9, 41: PRINT "    choice is high-lighted, press      "
LOCATE 10, 41: PRINT "    return.  (  ฤู )                   "
LOCATE 10, 56: PRINT CHR$(17)
LOCATE 11, 41: PRINT "    `TOOLS ...' and  `OTHER GAMES ...' "
LOCATE 12, 41: PRINT "    display more lists.                "
COLOR 14, 0: LOCATE 13, 41: PRINT "  OTHER GAMES & TOOLS:"
COLOR 3, 0: LOCATE 14, 41: PRINT "    Press the letter of your choice    "
LOCATE 15, 41: PRINT "    (shown next to the individual      "
LOCATE 16, 41: PRINT "    games). Pressing ` X ' switches to "
LOCATE 17, 41: PRINT "    back to the Games Listing. The     "
LOCATE 18, 41: PRINT "    heading of the list you are using  "
LOCATE 19, 41: PRINT "    is high-lighted.                   "
LOCATE 20, 41: PRINT "                                       "
GOTO LHS
END
PHELP:
 WIDTH 80
 T = 3
 GOTO START
END
PTOOL:
 WIDTH 80
 T = 4
 IF PTIME = 22 GOTO TOLRET
 GOTO START
REM TOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLS
REM TOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLSTOOLS
TOOL:
 COLOR 7, 0
 FOR R = 1 TO 23
 LOCATE R, 40
 PRINT CHR$(186)
 NEXT R
SIDE = 3
TOLBAK:
LOCATE 2, 1: COLOR 6, 1
PRINT "       G A M E S   L I S T I N G       "
PRINT "      อออออออออออออออออออออออออออ      "
LOCATE 1, 41: COLOR 1, 1
PRINT "                                       "
COLOR 12, 1: LOCATE 2, 41
PRINT "       T O O L S   L I S T I N G       "
LOCATE 3, 41
PRINT "      อออออออออออออออออออออออออออ      "
COLOR 1, 1: LOCATE 4, 41
PRINT "                                       "
IF PTIME = 22 GOTO TBRET
COLOR 4, 1: LOCATE 22, 1, 0
PRINT "                         PRESS THE LETTER OF YOUR CHOICE                        "
COLOR 11, 1: LOCATE 23, 1
PRINT "                        `X' SWITCHES TO THE GAMES LISTING                       "
LOCATE 7, 41: COLOR 2, 0
PRINT " (A)  MICROSOFT WORKS  (B)  PCTOOLS"
LOCATE 9, 41
PRINT " (C)  QUICK BASIC      (D)  VIEWMAX"
LOCATE 11, 41
PRINT " (E)  I.B.M. BASIC     (F)  SCAN"
LOCATE 13, 63: COLOR 8, 0
PRINT " (H)  WORDSTAR"
LOCATE 13, 41: COLOR 2, 0
PRINT " (G)  DOS DIRECTORY"
LOCATE 16, 15: COLOR 3, 7
PRINT "TOOLS ..."
TOLRET:
IF PTIME = 22 GOTO TOLBAK
TBRET:
SIDE = 3
DO
 O$ = INKEY$
 PRINT O$
LOOP UNTIL O$ = ""
GLOOP:
 A$ = INKEY$
 IF A$ <> "" THEN GOTO GOUT
GOTO GLOOP
GOUT:
IF A$ = "X" OR A$ = "x" GOTO PTAB
IF A$ = "A" OR A$ = "a" GOTO C1
IF A$ = "B" OR A$ = "b" GOTO C2
IF A$ = "C" OR A$ = "c" GOTO C3
IF A$ = "D" OR A$ = "d" GOTO C4
IF A$ = "E" OR A$ = "e" GOTO C5
IF A$ = "F" OR A$ = "f" GOTO C6
IF A$ = "G" OR A$ = "g" GOTO C7
IF A$ = "H" OR A$ = "h" GOTO GSORRY
GOTO GOUT
C1:
NAME "X" AS "C1": END
C2:
NAME "X" AS "C2": END
C3:
NAME "X" AS "C3": END
C4:
NAME "X" AS "C4": END
C5:
NAME "X" AS "C5": END
C6:
NAME "X" AS "C6": CHAIN "PASS"
END
C7:
NAME "X" AS "C7": CHAIN "PASS"
END
PTOL:
COLOR 7, 0
FOR k = 17 TO 20
  LOCATE k, 41: PRINT "                                      "
NEXT k
COLOR 6, 1: LOCATE 2, 41
PRINT "       T O O L S   L I S T I N G       "
LOCATE 3, 41
PRINT "      อออออออออออออออออออออออออออ      "
LOCATE 2, 1: COLOR 12, 1
PRINT "       G A M E S   L I S T I N G       "
PRINT "      อออออออออออออออออออออออออออ      "
GOSUB TOLA
PTIME = 22
GOTO LHS
END
PERR:
PRINT ERR
RUN
VEND:
END

