REM MENU
 LET TEST$ = "HELLO"
END
MENU:
LOCATE 1, 2: COLOR 7, 4: PRINT "ABOUT"
MP = 1
DO
 A$ = INKEY$
LOOP UNTIL A$ = ""
MLOOP:
 X$ = INKEY$
 IF X$ <> "" THEN GOTO MWHAT
GOTO MLOOP
MWHAT:
 IF X$ = "O" OR X$ = "o" THEN GOTO MLEFT
 IF X$ = "P" OR X$ = "p" THEN GOTO MRIGHT
 IF X$ = "S" OR X$ = "s" THEN GOTO MSLCT
 IF X$ = CHR$(27) THEN GOTO MEXIT
GOTO MLOOP
END
MLEFT:
 W = 1
 ON MP GOTO M1, M2, M3, M4, M5
END
MRIGHT:
 W = 2
 ON MP GOTO M1, M2, M3, M4, M5
END
M1:
 LOCATE 1, 2: COLOR 0, 3: PRINT "ABOUT": LOCATE 1, 2: COLOR 4, 3: PRINT "A"
 IF W = 1 THEN LOCATE 1, 36: COLOR 7, 4: PRINT "QUIT": MP = 5
 IF W = 2 THEN LOCATE 1, 9: COLOR 7, 4: PRINT "CHANGE": MP = 2
GOTO MLOOP
M2:
 LOCATE 1, 9: COLOR 0, 3: PRINT "CHANGE": LOCATE 1, 9: COLOR 4, 3: PRINT "C"
 IF W = 1 THEN LOCATE 1, 2: COLOR 7, 4: PRINT "ABOUT": MP = 1
 IF W = 2 THEN LOCATE 1, 17: COLOR 7, 4: PRINT "DOS CMNDS": MP = 3
GOTO MLOOP
M3:
 LOCATE 1, 17: COLOR 0, 3: PRINT "DOS CMNDS": LOCATE 1, 17: COLOR 4, 3: PRINT "D"
 IF W = 1 THEN LOCATE 1, 9: COLOR 7, 4: PRINT "CHANGE": MP = 2
 IF W = 2 THEN LOCATE 1, 30: COLOR 7, 4: PRINT "HELP": MP = 4
GOTO MLOOP
M4:
 LOCATE 1, 30: COLOR 0, 3: PRINT "HELP": LOCATE 1, 30: COLOR 4, 3: PRINT "H"
 IF W = 1 THEN LOCATE 1, 17: COLOR 7, 4: PRINT "DOS CMNDS": MP = 3
 IF W = 2 THEN LOCATE 1, 36: COLOR 7, 4: PRINT "QUIT": MP = 5
GOTO MLOOP
M5:
 LOCATE 1, 36: COLOR 0, 3: PRINT "QUIT": LOCATE 1, 36: COLOR 4, 3: PRINT "Q"
 IF W = 1 THEN LOCATE 1, 30: COLOR 7, 4: PRINT "HELP": MP = 4
 IF W = 2 THEN LOCATE 1, 2: COLOR 7, 4: PRINT "ABOUT": MP = 1
GOTO MLOOP

MSLCT:
IF MP = 1 THEN
 LOCATE 1, 2: COLOR 0, 3: PRINT "ABOUT": LOCATE 1, 3: COLOR 4, 3: PRINT "B"
 COLOR 4, 3
 LOCATE 2, 2: PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
 LOCATE 3, 2: PRINT "³ COMMENT       ³"
 LOCATE 4, 2: PRINT "³               ³"
 LOCATE 5, 2: PRINT "³ DOCUMENT FILE ³"
 LOCATE 6, 2: PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
COLOR 7, 4: LOCATE 3, 4: PRINT "COMMENT"

END IF
IF MP = 2 THEN
 GOTO FCHANGE
END IF
IF MP = 3 THEN
 LOCATE 1, 17: COLOR 0, 3: PRINT "DOS CMNDS": LOCATE 1, 17: COLOR 4, 3: PRINT "D"
 COLOR 4, 3
 LOCATE 2, 17: PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
 LOCATE 3, 17: PRINT "³ EDITOR      ³"
 LOCATE 4, 17: PRINT "ÃÄÄÄÄÄÄÄÄÄÄÄÄÄ´"
 LOCATE 5, 17: PRINT "³ CHKDSK      ³"
 LOCATE 6, 17: PRINT "³ DATE + TIME ³"
 LOCATE 7, 17: PRINT "³ FILELINK    ³"
 LOCATE 8, 17: PRINT "³ MEM         ³"
 LOCATE 9, 17: PRINT "³ MODE        ³"
 LOCATE 10, 17: PRINT "³ SET         ³"
 LOCATE 11, 17: PRINT "³ SID         ³"
 LOCATE 12, 17: PRINT "³ VOLUME      ³"
 LOCATE 13, 17: PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
COLOR 7, 4: LOCATE 3, 19: PRINT "EDITOR"

END IF

IF MP = 4 THEN
 LOCATE 1, 30: COLOR 0, 3: PRINT "HELP": LOCATE 1, 30: COLOR 4, 3: PRINT "H"
 PRINT "HELP": END
END IF
IF MP = 5 THEN
 LOCATE 1, 36: COLOR 0, 3: PRINT "QUIT": LOCATE 1, 36: COLOR 4, 3: PRINT "Q"
 COLOR 7, 0: CLS : WIDTH 80: SHELL: GOTO VSTART
END IF

MEXIT:
 LOCATE 1, 1: COLOR 0, 3: PRINT " ABOUT  CHANGE  DOS CMNDS    HELP  QUIT "
 COLOR 4, 3: LOCATE 1, 2: PRINT "A": LOCATE 1, 9: PRINT "C"
 LOCATE 1, 17: PRINT "D": LOCATE 1, 30: PRINT "H": LOCATE 1, 36: PRINT "Q"
IF LR = 23 THEN LOCATE P + 5, 23 ELSE LOCATE P + 6, 3
GOTO GETLOOP
END

