REM move
CLS

COLOR 2, 0
 LOCATE 1, 1: PRINT STRING$(80, 219)
COLOR 4, 0: LOCATE 1, 6: PRINT "GENERATING BOARD ....": COLOR 2, 0
 LOCATE 22, 1: PRINT STRING$(80, 219)
 FOR P = 2 TO 21
  LOCATE P, 1: PRINT CHR$(219)
  LOCATE P, 80: PRINT CHR$(219)
 NEXT P
 FOR Z = 1 TO INT(RND * 100)
  FOR Q = 1 TO INT(RND * 20)
   LET r = INT(RND * 80): IF r < 1 THEN LET r = 1: IF r > 79 THEN LET r = 78
   LET s = INT(RND * 20): IF s < 1 THEN LET s = 1: IF s > 20 THEN LET s = 18
  NEXT Q
  LOCATE s, r: PRINT CHR$(219)
 NEXT Z
LOCATE 1, 1: PRINT STRING$(80, 219)

COLOR 1, 0
LET SCORE = 0: LOCATE 1, 68: PRINT "SCORE: "; SCORE
LOCATE 1, 20: PRINT "ESCAPE TO EXIT"
LET r = 10: LET s = 10
LET X = 11: LET Y = 40
LOCATE X, Y: PRINT CHR$(219)
 LET r = INT(RND * 100): IF r > 79 THEN LET r = 78
 LET s = INT(RND * 100): IF s > 20 THEN LET s = 18
 COLOR 3, 0: LOCATE s, r: PRINT CHR$(176): COLOR 1, 0
GETLOOP:
 DO
  A$ = INKEY$
 LOOP UNTIL A$ = ""
 DO
  A$ = INKEY$
 LOOP WHILE A$ = ""

IF A$ = CHR$(0) + "P" THEN
  IF SCREEN(X + 1, Y, 0) = 219 THEN BEEP: GOTO GETLOOP
  LOCATE X, Y: PRINT " "
  LET X = X + 1: GOSUB FOOD
  LOCATE X, Y: COLOR 1, 0: PRINT CHR$(25)
 GOTO GETLOOP
END IF
IF A$ = CHR$(0) + "H" THEN
  IF SCREEN(X - 1, Y, 0) = 219 THEN BEEP: GOTO GETLOOP
  LOCATE X, Y: PRINT " "
  LET X = X - 1: GOSUB FOOD
  LOCATE X, Y: COLOR 1, 0: PRINT CHR$(24)
 GOTO GETLOOP
END IF
IF A$ = CHR$(0) + "M" THEN
  IF SCREEN(X, Y + 1, 0) = 219 THEN BEEP: GOTO GETLOOP
  LOCATE X, Y: PRINT " "
  LET Y = Y + 1: COLOR 1, 0: GOSUB FOOD
  LOCATE X, Y: PRINT CHR$(26)
 GOTO GETLOOP
END IF
IF A$ = CHR$(0) + "K" THEN
  IF SCREEN(X, Y - 1, 0) = 219 THEN BEEP: GOTO GETLOOP
  LOCATE X, Y: PRINT " "
  LET Y = Y - 1: GOSUB FOOD
  LOCATE X, Y: COLOR 1, 0: PRINT CHR$(27)
  GOTO GETLOOP
END IF
  IF A$ = CHR$(13) THEN
  GOSUB FIREUP
END IF
IF A$ = CHR$(27) THEN END
IF A$ = "E" OR A$ = "e" THEN END
GOTO GETLOOP

FOOD:
 IF SCREEN(X, Y, 0) = 176 OR SHT = 1 THEN
  BEEP
   LOCATE s, r: PRINT " "
   FOR Q = 1 TO INT(RND * 100)
    LET r = INT(RND * 100): IF r > 79 THEN LET r = 78
    LET s = INT(RND * 20): IF s < 1 THEN LET s = 1: IF s > 20 THEN LET s = 18
   NEXT Q
   COLOR 3, 0: LOCATE s, r: PRINT CHR$(176): COLOR 1, 0
  LET SCORE = SCORE + 1: LOCATE 1, 75: PRINT SCORE
 END IF
 SHT = 0
RETURN
FIREUP:
 
 IF SCREEN(X, Y, 0) = 24 THEN
  LET B = X - 1: LET V = Y: LOCATE B, V: COLOR 7, 0: PRINT "^"
  FOR j = 1 TO 100
   LOCATE B, V: PRINT " "
   IF B = 2 THEN RETURN
   LET B = B - 1
   IF SCREEN(B, V, 0) = 219 THEN RETURN
   IF SCREEN(B, V, 0) = 176 THEN SHT = 1: GOTO FOOD
  LOCATE B, V: COLOR 7, 0: PRINT CHR$(248)
  NEXT j
  COLOR 1, 0
  RETURN
 END IF
 IF SCREEN(X, Y, 0) = 25 THEN
  LET B = X + 1: LET V = Y: LOCATE B, V: COLOR 7, 0: PRINT "^"
  FOR j = 1 TO 100
   LOCATE B, V: PRINT " "
   IF B = 2 THEN RETURN
   LET B = B + 1
   IF SCREEN(B, V, 0) = 219 THEN RETURN
   IF SCREEN(B, V, 0) = 176 THEN SHT = 1: GOTO FOOD
  LOCATE B, V: COLOR 7, 0: PRINT CHR$(248)
  NEXT j
  COLOR 1, 0
  RETURN
 END IF
 IF SCREEN(X, Y, 0) = 26 THEN
  LET B = X: LET V = Y + 1: LOCATE B, V: COLOR 7, 0: PRINT CHR$(248)
  FOR j = 1 TO 100
   LOCATE B, V: PRINT " "
   IF B = 2 THEN RETURN
   LET V = V + 1
   IF SCREEN(B, V, 0) = 176 THEN SHT = 1: GOTO FOOD
   IF SCREEN(B, V, 0) = 219 THEN RETURN
  LOCATE B, V: COLOR 7, 0: PRINT CHR$(248)
  NEXT j
  COLOR 1, 0
  RETURN
 END IF
 IF SCREEN(X, Y, 0) = 27 THEN
  LET B = X: LET V = Y - 1: LOCATE B, V: COLOR 7, 0: PRINT CHR$(248)
  FOR j = 1 TO 100
   LOCATE B, V: PRINT " "
   IF B = 2 THEN RETURN
   LET V = V - 1
   IF SCREEN(B, V, 0) = 219 THEN RETURN
   IF SCREEN(B, V, 0) = 176 THEN SHT = 1: GOTO FOOD
  LOCATE B, V: COLOR 7, 0: PRINT CHR$(248)
  NEXT j
  COLOR 1, 0
  RETURN
 END IF

END

