REM INI
DIM LIN(9) AS STRING
CLS

GOTO INIPUT

OPEN "PASS.INI" FOR INPUT AS #1
 FOR X = 0 TO 9
  LINE INPUT #1, LIN(X)
 NEXT
CLOSE #1
FOR X = 0 TO 9
 PRINT LIN(X)
NEXT
END

INIPUT:
LET PASS$ = "wordilop"
PRINT PASS$
FOR X = 1 TO LEN(PASS$)
 MID$(PASS$, X, 1) = CHR$(ASC(MID$(PASS$, X, 1)) + 18)
 PRINT MID$(PASS$, X, 1);
NEXT X
 PRINT : PRINT PASS$

OPEN "PASS.INI" FOR OUTPUT AS #1
  PRINT #1, "Password=" + PASS$
  PRINT #1, "GuestExec=C:\WINDOWS\WIN.COM"
  PRINT #1, "PassExec1=C:\DOS\GLANCE.EXE"
  PRINT #1, "PassExec2="
CLOSE #1
END


REM ASC(MID$(PASS$, X, 1))+18


