REM pointer
DEFINT I-Z
SCREEN 1
RANDOMIZE TIMER
CLS
DIM IVERT(3, 11)
DIM IHORZ(21)

FOR I = 1 TO 100
 FOR J = 10 TO 12 STEP 2
  PSET (INT(RND * 640), INT(RND * 200)), J
 NEXT
NEXT

FOR I = 1 TO 3
 FOR J = 1 TO 11
  IVERT(I, J) = POINT(318 + I, 94 + J)
  PSET (318 + I, 94 + J), 15
 NEXT
NEXT

FOR I = 1 TO 21
 IHORZ(I) = POINT(309 + 1, 100)
 PSET (309 + I, 100), 15
NEXT

XLOC = 320: YLOC = 100

GETKEY:
DO
 X$ = INKEY$
LOOP WHILE X$ = ""
 IF X$ = CHR$(0) + "H" THEN GOTO UP
 IF X$ = CHR$(0) + "P" THEN GOTO DOWN
 IF X$ = CHR$(0) + "K" THEN GOTO RIGHT
 IF X$ = CHR$(0) + "M" THEN GOTO LEFT
GOTO GETKEY

UP:
 IF YLOC < 6 THEN GOTO GETKEY
 FOR I = 1 TO 3
  PSET (XLOC - 2 + I, YLOC + 5), IVERT(I, 11)
 NEXT
 FOR I = 1 TO 21
  PSET (XLOC - 11 + I, YLOC), IHORZ(I)
 NEXT
 FOR I = 1 TO 3
  FOR J = 10 TO 1 STEP -1
   IVERT(I, J + 1) = IVERT(I, J)
  NEXT
 NEXT
 YLOC = YLOC - 1
 FOR I = 1 TO 3
  IVERT(I, 1) = POINT(XLOC - 2 + I, YLOC - 5)
  PSET (XLOC - 2 + I, YLOC - 5), 15
 NEXT
 FOR I = 1 TO 21
  IHORZ(I) = POINT(XLOC - 11 + I, YLOC)
  PSET (XLOC - 11 + I, YLOC), 15
 NEXT
GOTO GETKEY

DOWN:
RIGHT:
LEFT:

