REM VIEW
CLS
LOCATE 1, 1: COLOR 0, 3
PRINT "                               TEXT  FILE  VIEWER                               "
LOCATE 23, 1: PRINT SPACE$(80)
LOCATE 23, 65: PRINT "ESC TO EXIT"
IF COMMAND$ <> "" THEN LET FILE$ = COMMAND$: GOTO SKIP
GOSUB GETFILE
SKIP:
COLOR 1, 3: LOCATE 23, 5: PRINT FILE$
VIEW PRINT 2 TO 22
COLOR 7, 0: LOCATE 2, 1

OPEN FILE$ FOR INPUT AS #1
FOR X = 1 TO 20
 IF EOF(1) = -1 THEN GOTO PLOOP
 INPUT #1, LINE$
 PRINT LINE$
NEXT X

PLOOP:
DO
 A$ = INKEY$
LOOP UNTIL A$ = ""
DO
 A$ = INKEY$
LOOP WHILE A$ = ""
 IF A$ = CHR$(0) + "P" THEN
  IF EOF(1) = -1 THEN GOTO PLOOP
  INPUT #1, LINE$
  PRINT LINE$
  GOTO PLOOP
 END IF
 IF A$ = CHR$(0) + "Q" THEN
  FOR X = 1 TO 20
   IF EOF(1) = -1 THEN GOTO PLOOP
   INPUT #1, LINE$
   PRINT LINE$
  NEXT X
  GOTO PLOOP
 END IF
 IF A$ = CHR$(27) THEN CLOSE #1: CLS : END
 IF A$ = CHR$(0) + "G" THEN
  SEEK #1, 1: CLS
   FOR X = 1 TO 20
    INPUT #1, LINE$: PRINT LINE$
   NEXT X
  GOTO PLOOP
 END IF
GOTO PLOOP
END

PERR:
 IF ERR = 53 THEN GOTO PLOOP
LOCATE 10, 40
COLOR 0, 7
PRINT ERR
END

GETFILE:
 COLOR 14, 0
 LOCATE 11, 24: PRINT "ษอออENTER NAME OF FILE TO VIEWอออป"
 LOCATE 12, 24: PRINT "บ         ฏ            ฎ         บ"
 LOCATE 13, 24: PRINT "ศออออออออออออออออออออออออออออออออผ"
 COLOR 0, 6: LOCATE 11, 28: PRINT "ENTER NAME OF FILE TO VIEW"
 COLOR 4, 0: LOCATE 12, 35: INPUT ; "", FILE$
 FOR X = 11 TO 13
  LOCATE X, 24: PRINT SPACE$(34)
 NEXT X
RETURN
END

