all:
	gcc -L/usr/X11R6/lib -I/usr/X11R6/include mandel.c -lX11 -o mandel
old:
	gcc -L/usr/X11R6/lib -I/usr/X386/include simon/manlib.o mandel1.c -lX11 -o mandel1
example:
	gcc -L/usr/X11R6/lib -I/usr/X386/include example.c -lX11 -o example
